/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import java.sql.*;
import javax.swing.*;
import javax.xml.crypto.Data;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC04
 */

public class penjualanbarang extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statpjln;
    Boolean ada = false;

private void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/transaksi_athallah";
        String user = "root";
        String pass = "";
        con = DriverManager.getConnection(url, user, pass);
        statpjln = con.createStatement(rs.TYPE_SCROLL_SENSITIVE, rs.CONCUR_UPDATABLE);
        rs = statpjln.executeQuery("select * from barang");
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
        System.exit(0);
    }
}
private void display(){
    try {
        String sql = "select * from barang WHERE stok > 0;";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
    
    public penjualanbarang() {
        initComponents();
        koneksi();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jtextfield1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jtextfield5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jtextfield2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jtextfield3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jtextfield4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("DATA MASTER BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel2.setText("Total Harga");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, -1));

        Jtextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtextfield1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("TRANSAKSI PENJUALAN BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel4.setText("Pencarian");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        Jtextfield5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtextfield5ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtextfield5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 120, -1));

        jLabel5.setText("ID Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        Jtextfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtextfield2ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtextfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        Jtextfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtextfield3ActionPerformed(evt);
            }
        });
        getContentPane().add(Jtextfield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, -1));

        jLabel7.setText("Jumlah barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        Jtextfield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtextfield4ActionPerformed(evt);
            }
        });
        Jtextfield4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jtextfield4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtextfield4KeyTyped(evt);
            }
        });
        getContentPane().add(Jtextfield4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 420, 210));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("MASUKKAN DATA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtextfield1ActionPerformed

    private void Jtextfield5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtextfield5ActionPerformed
        
    }//GEN-LAST:event_Jtextfield5ActionPerformed

    private void Jtextfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtextfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtextfield2ActionPerformed

    private void Jtextfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtextfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtextfield3ActionPerformed

    private void Jtextfield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtextfield4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtextfield4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            koneksi();
            int row = jTable1.getSelectedRow();
            String tabel_klik = (jTable1.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * From barang where id_barang='" + tabel_klik + "'");
            if (sql.next()) {
//                String nama = sql.getString("nama_barang");
//                Jtextfield1.setText(nama);
                String id = sql.getString("id_barang");
                Jtextfield2.setText(id);
//              jTextField1.setEditable(false);
                String harga = sql.getString("harga");
                Jtextfield3.setText(harga);
                
                Jtextfield4.setText("");
                Jtextfield5.setText("");
            }
            
        } catch (Exception e){
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void Jtextfield4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtextfield4KeyTyped
        
    }//GEN-LAST:event_Jtextfield4KeyTyped

    private void Jtextfield4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtextfield4KeyReleased
        try {
            int angka1, angka2, hasil;
             angka1 = Integer.parseInt(Jtextfield3.getText());
             angka2 = Integer.parseInt(Jtextfield4.getText());
            
            hasil = angka1 * angka2;
            
            Jtextfield5.setText(Integer.toString(hasil));
            
            
        } catch (Exception exc){
            
        }
    }//GEN-LAST:event_Jtextfield4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualanbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualanbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualanbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualanbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualanbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtextfield1;
    private javax.swing.JTextField Jtextfield2;
    private javax.swing.JTextField Jtextfield3;
    private javax.swing.JTextField Jtextfield4;
    private javax.swing.JTextField Jtextfield5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
